export enum Services{
    CONVERSATIONS = "CONVERSATIONS_SERVICE",
    PARTICIPANT = "PARTICIPANT_SERVICE",
    USERS = "USERS_SERVICE",
    MESSAGES = "MESSAGES_SERVICE",
    GATEWAY_SESSION_MANAGER = "GATEWAY_SESSION_MANAGER",
    FRIENDS = "FRIENDS_SERVICE",
    FRIENDS_REQUESTS = "FRIENDS_REQUESTS_SERVICE",
    AUTH = "AUTH_SERVICE",
    PROFILE = "PROFILE_SERVICE",
    GROUPS = "GROUPS_SERVICE",


}